<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Exercise - `pandas` Long Format, Wide Format, Pivot Tables, and Melting
---

## Exercise:

#### 1. Convert the NPAS_parsed_trunc_long.csv dataset from long to wide

In [5]:
# load the data
import pandas as pd
nerdy = pd.read_csv('./data/NPAS_parsed_trunc_long.csv')

In [6]:
# check the head
nerdy.head()

   subject_id   variable value
0           1  education   4.0
1           2  education   3.0
2           5  education   2.0
3           6  education   2.0
4           7  education   2.0

In [7]:
# check shape
nerdy.shape

(70295, 3)

You can see that the long format data has far more rows than the wide data set but only three columns.

Below you can view the three columns: `subject_id`, `variable`, and `value`.

**`subject_id:`**
- This is the primary "key" or `ID` column. Each `subject_id` will have corresponding entries in the `variable` column — one for each row.

**`variable:`**
- This column indicates the variable with which the item in the `value` column corresponds.

**`value:`**

- This contains all values for all variables for all IDs. Essentially, every cell in the wide data set except the `subject_id` is listed in this column.

In [8]:
# filter subject_id ==1

nerdy[nerdy['subject_id'] == 1]

       subject_id                      variable       value
0               1                     education         4.0
700             1                         urban         2.0
1400            1                        gender         2.0
2100            1                        engnat         1.0
2800            1                           age        50.0
3500            1                          hand         1.0
4200            1                      religion         1.0
4900            1                         voted         1.0
5600            1                       married         1.0
6300            1                    familysize         3.0
7000            1                         major  biophysics
7701            1                    race_white         1.0
9092            1                    race_nerdy         0.0
10483           1          race_native_american         0.0
11874           1                 writing_novel         1.0
13265           1             read_tech_reports         4.0
14656           1          online_over_inperson         3.0
16047           1                 introspective         3.0
17438           1           hobbies_over_people         1.0
18829           1            books_over_parties         4.0
20220           1                       bookish         4.0
21611           1    libraries_over_publicspace         5.0
23002           1       race_native_austrailian         0.0
24393           1            like_hard_material         3.0
25784           1                 race_hispanic         0.0
27175           1            diagnosed_autistic         2.0
28566           1          play_many_videogames         1.0
29957           1                     race_arab         0.0
31348           1                    race_asian         0.0
32739           1            interested_science         4.0
34130           1                   playes_rpgs         4.0
35521           1           in_advanced_classes         4.0
36912           1                 collect_books         5.0
38303           1  intelligence_over_appearance         3.0
39694           1           watch_science_shows         5.0
41085           1          academic_over_social         2.0
42476           1          like_science_fiction         4.0
43867           1               like_dry_topics         1.0
45258           1                    race_black         0.0
46649           1                          calm         6.0
48040           1                  disorganized         5.0
49431           1                   extraverted         5.0
50822           1                    dependable         5.0
52213           1                      critical         3.0
53604           1                     opennness         5.0
54995           1                       anxious         4.0
56386           1                   sympathetic         5.0
57777           1                      reserved         5.0
59168           1                  conventional         1.0
60559           1                 was_odd_child         3.0
61950           1       prefer_fictional_people         3.0
63341           1                enjoy_learning         3.0
64732           1        excited_about_research         4.0
66123           1                strange_person         4.0
67514           1              like_superheroes         4.0
68905           1              socially_awkward         5.0

**Print out the unique values in the `variable` column.**

You can see that the unique values in the `variable` column correspond to the column headers in the wide format data.

In [14]:
# show unique values in the variable column

nerdy['variable'].value_counts()
# or nerdy['variable'].unique()

variable
race_white                      1391
race_nerdy                      1391
race_native_american            1391
writing_novel                   1391
read_tech_reports               1391
online_over_inperson            1391
introspective                   1391
hobbies_over_people             1391
books_over_parties              1391
bookish                         1391
libraries_over_publicspace      1391
race_native_austrailian         1391
like_hard_material              1391
race_hispanic                   1391
diagnosed_autistic              1391
play_many_videogames            1391
race_arab                       1391
race_asian                      1391
interested_science              1391
playes_rpgs                     1391
in_advanced_classes             1391
collect_books                   1391
intelligence_over_appearance    1391
watch_science_shows             1391
academic_over_social            1391
like_science_fiction            1391
like_dry_topics                 1391
race_black                      1391
calm                            1391
disorganized                    1391
extraverted                     1391
dependable                      1391
critical                        1391
opennness                       1391
anxious                         1391
sympathetic                     1391
reserved                        1391
conventional                    1391
was_odd_child                   1391
prefer_fictional_people         1391
enjoy_learning                  1391
excited_about_research          1391
strange_person                  1391
like_superheroes                1391
socially_awkward                1391
education                        700
urban                            700
gender                           700
engnat                           700
age                              700
hand                             700
religion                         700
voted                            700
married                          700
familysize                       700
major                            700
Name: count, dtype: int64

 **Convert from long to wide**

In [13]:
nerdy.head()

   subject_id   variable value
0           1  education   4.0
1           2  education   3.0
2           5  education   2.0
3           6  education   2.0
4           7  education   2.0

In [15]:
# convert from long to wide
# convert the dataset back from wide to long using pd.pivot
nerdy_wide = nerdy.pivot(index = 'subject_id',
                            columns = 'variable',
                            values = 'value').reset_index()

# check the head
nerdy_wide.head()

variable,subject_id,academic_over_social,age,anxious,bookish,books_over_parties,calm,collect_books,conventional,critical,...,religion,reserved,socially_awkward,strange_person,sympathetic,urban,voted,was_odd_child,watch_science_shows,writing_novel
0,0,5.0,NaN,1.0,5.0,5.0,7.0,5.0,1.0,1.0,...,NaN,7.0,5.0,5.0,7.0,NaN,NaN,5.0,5.0,3.0
1,1,2.0,50.0,4.0,4.0,4.0,6.0,5.0,1.0,3.0,...,1.0,5.0,5.0,4.0,5.0,2.0,1.0,3.0,5.0,1.0
2,2,5.0,22.0,7.0,5.0,5.0,2.0,5.0,1.0,6.0,...,1.0,7.0,5.0,5.0,2.0,1.0,1.0,5.0,5.0,4.0
3,3,5.0,NaN,4.0,4.0,5.0,7.0,5.0,1.0,2.0,...,NaN,2.0,5.0,5.0,6.0,NaN,NaN,5.0,5.0,4.0
4,4,4.0,NaN,3.0,5.0,5.0,6.0,4.0,2.0,5.0,...,NaN,6.0,0.0,5.0,5.0,NaN,NaN,5.0,4.0,1.0

In [16]:
# check the shape of the new created wide dataframe
nerdy_wide.shape

(1391, 57)

In [17]:
# Remove the column label
nerdy_wide.columns.name = None
# check the head again
nerdy_wide.head()

,subject_id,academic_over_social,age,anxious,bookish,books_over_parties,calm,collect_books,conventional,critical,...,religion,reserved,socially_awkward,strange_person,sympathetic,urban,voted,was_odd_child,watch_science_shows,writing_novel
0,0,5.0,NaN,1.0,5.0,5.0,7.0,5.0,1.0,1.0,...,NaN,7.0,5.0,5.0,7.0,NaN,NaN,5.0,5.0,3.0
1,1,2.0,50.0,4.0,4.0,4.0,6.0,5.0,1.0,3.0,...,1.0,5.0,5.0,4.0,5.0,2.0,1.0,3.0,5.0,1.0
2,2,5.0,22.0,7.0,5.0,5.0,2.0,5.0,1.0,6.0,...,1.0,7.0,5.0,5.0,2.0,1.0,1.0,5.0,5.0,4.0
3,3,5.0,NaN,4.0,4.0,5.0,7.0,5.0,1.0,2.0,...,NaN,2.0,5.0,5.0,6.0,NaN,NaN,5.0,5.0,4.0
4,4,4.0,NaN,3.0,5.0,5.0,6.0,4.0,2.0,5.0,...,NaN,6.0,0.0,5.0,5.0,NaN,NaN,5.0,4.0,1.0

In [18]:
# save wide data to csv as nerdy_wide.csv
nerdy_wide.to_csv('./data/nerdy_wide.csv')

#### 2. Convert it back from wide to long
- Keep `subject_id` and `major` as the `Columns that stay locked`

In [19]:
# check the head of nerdy_wide
nerdy_wide.head()

,subject_id,academic_over_social,age,anxious,bookish,books_over_parties,calm,collect_books,conventional,critical,...,religion,reserved,socially_awkward,strange_person,sympathetic,urban,voted,was_odd_child,watch_science_shows,writing_novel
0,0,5.0,NaN,1.0,5.0,5.0,7.0,5.0,1.0,1.0,...,NaN,7.0,5.0,5.0,7.0,NaN,NaN,5.0,5.0,3.0
1,1,2.0,50.0,4.0,4.0,4.0,6.0,5.0,1.0,3.0,...,1.0,5.0,5.0,4.0,5.0,2.0,1.0,3.0,5.0,1.0
2,2,5.0,22.0,7.0,5.0,5.0,2.0,5.0,1.0,6.0,...,1.0,7.0,5.0,5.0,2.0,1.0,1.0,5.0,5.0,4.0
3,3,5.0,NaN,4.0,4.0,5.0,7.0,5.0,1.0,2.0,...,NaN,2.0,5.0,5.0,6.0,NaN,NaN,5.0,5.0,4.0
4,4,4.0,NaN,3.0,5.0,5.0,6.0,4.0,2.0,5.0,...,NaN,6.0,0.0,5.0,5.0,NaN,NaN,5.0,4.0,1.0

In [25]:
# do the convert
nerdy_long = pd.melt(frame = nerdy_wide,
                    id_vars = 'subject_id',
                    value_vars = nerdy_wide.columns.to_list()[1:], # we can work without it because by defult will choose all the rest
                    var_name = 'variable',
                    value_name = 'value')

# check the head
nerdy_long.head()

   subject_id              variable value
0           0  academic_over_social   5.0
1           1  academic_over_social   2.0
2           2  academic_over_social   5.0
3           3  academic_over_social   5.0
4           4  academic_over_social   4.0

In [26]:
# get the shape of the dataset
nerdy_long.shape

(77896, 3)

In [27]:
nerdy.shape

(70295, 3)

#### 3. Convert again from wide to long but with a selected value_vars
- Create the same DataFrame with `.melt()` on the full wide data set, but select the columns 'anxious','bookish','calm' to be used with the `value_vars` argument
- name the new dataframe with a different name than the previous

In [28]:
# do the convert, call the dataframe with some other name
nerdy_long2 = pd.melt(frame = nerdy_wide,
                    id_vars = 'subject_id',
                    value_vars = ['anxious','bookish','calm'],
                    var_name = 'variable',
                    value_name = 'value')

# check the head
nerdy_long2

      subject_id variable value
0              0  anxious   1.0
1              1  anxious   4.0
2              2  anxious   7.0
3              3  anxious   4.0
4              4  anxious   3.0
...          ...      ...   ...
4168        1386     calm   3.0
4169        1387     calm   6.0
4170        1388     calm   5.0
4171        1389     calm   4.0
4172        1390     calm   6.0

[4173 rows x 3 columns]

In [29]:
# get the shape of the dataset
nerdy_long2.shape

(4173, 3)